### ISSUE TITLE
about the dataSet

### ISSUE THREAD

**Issue by DEMON3** [sustecha/LOF_OCSVM#1]
I want to try your dataset. Can you give it to me? Thankyou very much~

**Comment by reemelmahdi** [comment]
I got the dataset from Kaggle, please find the link below:
https://www.kaggle.com/mlg-ulb/creditcardfraud
Now you will be able to know the data and how its structured!
Sorry for the late reply!

**Comment by DEMON3** [comment]
Very Useful, Thank you~
